name: "Validate Gradle Wrapper"
on:
    push:
        branches:
            - main
        paths:
            - '**/gradle/**'
    pull_request:
        branches: [main]
        paths:
            - '**/gradle/**'

jobs:
    validation:
        name: "Gradle Wrapper Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: gradle/wrapper-validation-action@v1
